### PR TITLE
fix CRX extensions for Chromium

### PR DESCRIPTION
**Pull request by ghost**
I'm not sure if this is the correct way to do it, but this fixes installing extensions via the Chromium Web Store (https://github.com/NeverDecaf/chromium-web-store)

### CODE REVIEW

**Comment by nobody43** [comment]
I suggest to try with `owner` first.

**Comment by ghost** [comment]
Done! I've also renamed com.google.Chrome to org.chromium.Chromium just in case

**Comment by nobody43** [comment]
Good. The behavior might differ though - make sure it's working the same.
And I can't merge it, just to be clear. :)

**Comment by ghost** [comment]
I've tested it by reinstalling the web store extension, seems to be working fine.

**Comment by ghost** [comment]
FYI there's also /tmp/.org.chromium.Chromium.* which contains SingletonCookie/SingletonSocket, but I'm not sure if that's necessary?

**Comment by nobody43** [comment]
I can't tell for sure. Chromium is such a monstrosity it can spread everywhere.

**Comment by nibags** [comment]
Thanks for your collaboration! I will integrate them.
Chromium is very large and it's difficult to make one AppArmor profile work for all users. It's best to tailor the profile for the features and extensions you personally use.

**Pull request merged**
